#!/bin/sh

SCRIPT_PATH=`readlink -f $0`
SCRIPT_DIR=`dirname $SCRIPT_PATH`

source $SCRIPT_DIR/setenv

{
    
    echo "****** derby.ddl.persistence.sql diff start ******"
    diff ${TS_HOME}/sql/derby/derby.ddl.persistence.sql ${SCRIPT_DIR}/derby.ddl.persistence.sql
    echo "****** derby.ddl.persistence.sql diff end ******"
    echo "Overwriting ${TS_HOME}/sql/derby/derby.ddl.persistence.sql with ${SCRIPT_DIR}/derby.ddl.persistence.sql"
    # save a copy of the original
    cp ${TS_HOME}/sql/derby/derby.ddl.persistence.sql ${SCRIPT_DIR}/derby.ddl.persistence.sql-orig
    cp ${SCRIPT_DIR}/derby.ddl.persistence.sql ${TS_HOME}/sql/derby/derby.ddl.persistence.sql
    set ts.home=${TS_HOME}
    ./gradlew clean syncDeps
    cd $TS_HOME/bin
    ${ANT_HOME}/bin/ant -f initdb.xml init.derby
    echo "Restoring original ${TS_HOME}/sql/derby/derby.ddl.persistence.sql"
    cp ${SCRIPT_DIR}/derby.ddl.persistence.sql-orig ${TS_HOME}/sql/derby/derby.ddl.persistence.sql
}
