#!/bin/bash

#SCRIPT_PATH=`readlink -f $0`
#SCRIPT_DIR=`dirname $SCRIPT_PATH`
SCRIPT_DIR=`pwd`

#source $SCRIPT_DIR/setenv

OUTPUT_PATH=$SCRIPT_DIR/logging/orm-test-output.txt

rm -f $OUTPUT_PATH
mkdir -p $SCRIPT_DIR/logging/

(
    cd $SCRIPT_DIR
    gradle syncDeps &>$OUTPUT_PATH
)


{
    echo "TS_HOME=${TS_HOME}"
    TEST_PATH="$TS_HOME/src/com/sun/ts/tests/jpa"

    if [ "$1" != "" ]; then
        TEST_PATH=$TEST_PATH/$1
##        echo "Running tests [$1] using TEST_PATH=$TEST_PATH"
##    else 
##        echo "Running all tests using TEST_PATH=$TEST_PATH"
    fi


    cd $TEST_PATH

##echo "Using ant from [`which ant`]"

    ant runclient -Dfailonerror=false &>$OUTPUT_PATH
}
