#!/bin/sh

#SCRIPT_DIR=`dirname $0`
SCRIPT_DIR=`pwd`

## Custom values
export TCK_HOME=${SCRIPT_DIR}
echo "TCK_HOME=${TCK_HOME}"

export DERBY_HOME=${SCRIPT_DIR}/derby
echo "DERBY_HOME=${DERBY_HOME}"

export DERBY_DB_HOME=${DERBY_HOME}/derby-db
echo "DERBY_DB_HOME=${DERBY_DB_HOME}"

## Values that the TCK expects to be set
export TS_HOME=$TCK_HOME/persistence-tck
echo "TS_HOME=${TS_HOME}"

export ANT_HOME=${TCK_HOME}/ant
echo "ANT_HOME=${ANT_HOME}"

export PATH=${TS_HOME}/bin:${ANT_HOME}/bin:$PATH
echo "PATH=${PATH}"
