#!/bin/bash

SCRIPT_PATH=`readlink -f $0`
SCRIPT_DIR=`dirname $SCRIPT_PATH`

OUTPUT_FILE=$SCRIPT_DIR/logging/sig-test-output.txt

{
    rm -f $OUTPUT_FILE
    mkdir -p $SCRIPT_DIR/logging/

    cd $TS_HOME/src/com/sun/ts/tests/signaturetest

##    echo "Using ant from [`which ant`]"
    ant runclient -Dfailonerror=false &>$OUTPUT_FILE
}
